openapi: 3.0.3
info:
  title: Gymer - OpenAPI 3.0
  description: This is the Gymer API, built using the OpenAPI 3.0 specification. This API empowers fitness enthusiasts to log, track, and analyze their workout history with ease. Whether you're managing user profiles, recording exercise sessions, or customizing workout plans, this API is designed to streamline your fitness tracking process.
  
    In this iteration, we’ve adopted a design-first approach, ensuring that the API is intuitive, well-documented, and robust. You can help us enhance the API by providing feedback, suggesting improvements to the definition, or contributing to the codebase.
    
    Together, we can evolve the Gymer API to better serve fitness communities and deliver exciting new features through OpenAPI 3.0 standards. Let’s build a healthier world, one endpoint at a time!
  
  version: 1.0.0
servers:
- url: https://gymer.blabla/api/
tags:
- name: exercise
  description: Everything about your exercises
  externalDocs:
    description: Find out more
    url: http://swagger.io
- name: history
  description: Access to exercisehistory orders
  externalDocs:
    description: Find out more about our history
    url: http://swagger.io
- name: auth
  description: Operations about authentication
paths:
  /exercise:
    get:
      tags:
      - exercise
      summary: View all exercise
      responses:
        '200':
          description: Exercises retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetExercises'
        '400':
          description: Failed to retrieve exercises
        '404':
          description: No exercises found
        '500':
          description: Unexpected server error
      security:
      - gymer_auth:
        - read:exercises
  /exercise/{id_exercise}:
    get:
      tags:
      - exercise
      summary: Find exercise by ID
      parameters:
      - name: id_exercise
        in: path
        required: true
        schema:
          type: integer
          format: int8
      responses:
        '200':
          description: Exercises retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetExercise'
        '400':
          description: Failed to retrieve exercises
        '404':
          description: No exercises found
        '500':
          description: Unexpected server error
      security:
      - gymer_auth:
        - read:exercises
  /history:
    post:
      tags:
      - history
      summary: Add a history
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PostHistory'
        '400':
          description: All fields are required and exercises must be an array.
    get:
      tags:
      - history
      summary: View all history
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetHistories'
        '400':
          description: Invalid input
        '422':
          description: Validation exception
  /history/{id_history}:
    get:
      tags:
      - history
      summary: Find history by ID
      parameters:
      - name: id_history
        in: path
        description: ID of order that needs to be fetched
        required: true
        schema:
          type: integer
          format: int8
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PostHistory'
        '404':
          description: Order not found
        '500':
          description: Unexpected server error / Failed to update history
    put:
      tags:
      - history
      summary: Update history by ID
      parameters:
      - name: id_history
        in: path
        description: ID of the order that needs to be update
        required: true
        schema:
          type: integer
          format: int8
      requestBody:
        description: Update an existent exercise log in the history
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReqBodyUpdateHistory'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PostHistory'
        '404':
          description: History not found
        '500':
          description: Unexpected server error / Failed to update history
    delete:
      tags:
      - history
      summary: Delete history by ID
      parameters:
      - name: id_history
        in: path
        description: ID of the history that needs to be deleted
        required: true
        schema:
          type: integer
          format: int8
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PostHistory'
        '404':
          description: History not found
        '500':
          description: Unexpected server error / Failed to update history
  /auth/register:
    post:
      tags:
      - auth
      summary: Create user
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReqBodyRegister'
      responses:
        default:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegisterResp'
  /auth/login:
    post:
      tags:
      - auth
      summary: Login user
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReqBodyLogin'
      responses:
        default:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResp'
  /auth/forgot-password:
    post:
      tags:
      - auth
      summary: Forgot password handler
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReqBodyForgotPass'
      responses:
        default:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ForgotPassResp'
  /auth/reset-password:
    post:
      tags:
      - auth
      summary: Verification and change password
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReqBodyResetPass'
      responses:
        default:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResetPassResp'
  /plan:
    post:
      tags:
      - plan
      summary: Create Plan
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReqBodyCreatePlan'
      responses:
        default:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreatePlanResp'
    get:
      tags:
      - plan
      summary: Create Plan
      responses:
        default:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreatePlanResp'
  /plan/{id_jadwal}:
    put:
      tags:
      - plan
      summary: Find history by ID
      parameters:
      - name: id_jadwal
        in: path
        required: true
        schema:
          type: integer
          format: int8
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReqBodyUpdatePlan'
      responses:
        default:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreatePlanResp'
    delete:
      tags:
      - plan
      summary: Find history by ID
      parameters:
      - name: id_jadwal
        in: path
        required: true
        schema:
          type: integer
          format: int8
      responses:
        default:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeletePlanResp'
  /user:
    get:
      tags:
      - user
      summary: Find all users
      responses:
        default:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetUsers'
  /user/{user_id}:
    get:
      tags:
        - user
      summary: Find user by ID
      parameters:
      - name: user_id
        in: path
        required: true
        schema:
          type: integer
          format: int8
      responses:
        default:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetUser'
    put:
      tags:
        - user
      summary: Find user by ID
      parameters:
      - name: user_id
        in: path
        required: true
        schema:
          type: integer
          format: int8
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReqBodyUpdateUser'
      responses:
        default:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetUser'
    delete:
      tags:
        - user
      summary: Find user by ID
      parameters:
      - name: user_id
        in: path
        required: true
        schema:
          type: integer
          format: int8
      responses:
        default:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeleteUserResp'
components:
  schemas:
    GetUsers:
      allOf:
      - $ref: '#/components/schemas/BaseResponse'
      - $ref: '#/components/schemas/DataUsers'
    GetUser:
      allOf:
      - $ref: '#/components/schemas/BaseResponse'
      - $ref: '#/components/schemas/DataUser'
    GetExercises:
      allOf:
      - $ref: '#/components/schemas/BaseResponse'
      - $ref: '#/components/schemas/DataExercises'
    GetExercise:
      allOf:
      - $ref: '#/components/schemas/BaseResponse'
      - $ref: '#/components/schemas/DataExercise'
    PostHistory:
      allOf:
      - $ref: '#/components/schemas/BaseResponse'
      - $ref: '#/components/schemas/DataHistory'
    GetHistories:
      allOf:
      - $ref: '#/components/schemas/BaseResponse'
      - $ref: '#/components/schemas/DataHistories'
    LoginResp:
      allOf:
      - $ref: '#/components/schemas/BaseResponse'
      - $ref: '#/components/schemas/TokenLogin'
    RegisterResp:
      allOf:
      - $ref: '#/components/schemas/BaseResponse'
      - $ref: '#/components/schemas/RegisterDataResp'
    ForgotPassResp:
      allOf:
      - $ref: '#/components/schemas/BaseResponse'
      - $ref: '#/components/schemas/ForgotPassMessage'
    ResetPassResp:
      allOf:
      - $ref: '#/components/schemas/BaseResponse'
      - $ref: '#/components/schemas/ResetPassMessage'
    DeleteUserResp:
      allOf:
      - $ref: '#/components/schemas/BaseResponse'
      - $ref: '#/components/schemas/DeleteUserMessage'
    CreatePlanResp:
      allOf:
      - $ref: '#/components/schemas/BaseResponse'
      - $ref: '#/components/schemas/CreatePlanData'
    DeletePlanResp:
      allOf:
      - $ref: '#/components/schemas/BaseResponse'
      - $ref: '#/components/schemas/DeletePlanData'
    ReqBodyRegister:
      allOf:
      - $ref: '#/components/schemas/ReqBodyLogin'
      - $ref: '#/components/schemas/UserData'
    BaseResponse:
      type: object
      properties:
        statusCode:
          type: integer
          example: 200
        success:
          type: boolean
          example: true
        message:
          type: string
          example: success
    DataExercises:
      type: object
      properties:
        data:
          type: array
          items: {}
          example:
          - id_exercise: 1
            created_at: '2024-12-06T14:49:21.006903+00:00'
            nama_alat: chest fly machine
            bagian_tubuh: null
            gambar: https://storage.googleapis.com/exercise-image/exercise-gif/chest%20fly%20machine/bent%20over%20lateral%20raise.gif
            nama_exercise: bent over lateral raise
          - id_exercise: 2
            created_at: '2024-12-06T14:49:58.600455+00:00'
            nama_alat: chest fly machine
            bagian_tubuh: null
            gambar: https://storage.googleapis.com/exercise-image/exercise-gif/chest%20fly%20machine/lever%20seated%20fly.gif
            nama_exercise: lever seated fly
    DataUsers:
      type: object
      properties:
        data:
          type: array
          items: {}
          example:
          - id_user: 30
            created_at: "2024-12-08T13:27:22.096117+00:00"
            gender: "P"
            berat_badan: 12.1
            tinggi_badan: 13.3
            email: "idessert90@gmail.com"
            phone_number: "18201281"
            name: "asd"
          - id_user: 31
            created_at: "2024-12-09T10:07:05.916156+00:00"
            gender: "L"
            berat_badan: 12.1
            tinggi_badan: 13.3
            email: "dickyzaldyharyanto@gmail.com"
            phone_number: "18201281"
            name: "dicky"
    DataUser:
      type: object
      properties:
        data:
          type: array
          items: {}
          example:
          - id_user: 30
            created_at: "2024-12-08T13:27:22.096117+00:00"
            gender: "P"
            berat_badan: 12.1
            tinggi_badan: 13.3
            email: "idessert90@gmail.com"
            phone_number: "18201281"
            name: "asd"
    DataExercise:
      type: object
      properties:
        data:
          type: object
          example:
            id_exercise: 3
            created_at: '2024-12-06T14:50:17.829604+00:00'
            nama_alat: dumbell
            bagian_tubuh: back
            gambar: https://storage.googleapis.com/exercise-image/exercise-gif/dumbell/back/dumbbell%20row%20on%20incline%20bench.gif
            nama_exercise: dumbbell row on incline bench
    CreatePlanData:
      type: object
      properties:
        data:
          type: object
          properties:
            id_jadwal:
              type: integer
              example: 3
            created_at:
              type: integer
              example: 2024-12-12T17:58:17.70032+00:00
            id_user:
              type: integer
              example: 30
            id_exercise:
              type: integer
              example: 24
            tanggal:
              type: string
              format: date
              example: 2021-12-23
            repetisi:
              type: integer
              example: 1
    DeletePlanData:
      type: object
      properties:
        data:
          type: object
          properties:
            deletedPlan:
              type: array
              items: {}
              example: 
                id_jadwal: 3
                created_at: 2024-12-12T17:58:17.70032+00:00
                id_user: 30
                id_exercise: 24
                tanggal: 2021-12-23
                repetisi: 1
    DataHistory:
      type: object
      properties:
        data:
          type: array
          items: {}
          example:
            id_history: 4
            created_at: '2024-12-09T07:00:26.8963+00:00'
            detil_history:
              date: '2024-12-05'
              duration: 1h 30m
              exercises:
              - exercise_name: dumbbell row on incline bench
                sets:
                - repetitions: 10
                  weight: 50
                - repetitions: 8
                  weight: 55
                - repetitions: 6
                  weight: 60
              - exercise_name: concentrated curl
                sets:
                - repetitions: 12
                  weight: 100
                - repetitions: 10
                  weight: 110
                - repetitions: 8
                  weight: 120
            id_user: 30
    DataHistories:
      type: object
      properties:
        data:
          type: array
          items: {}
          example:
          - id_history: 2
            created_at: '2024-12-09T03:09:16.034498+00:00'
            detil_history:
              date: '2024-12-05'
              duration: 1h 30m
              exercises:
              - exercise_name: Pressto
                sets:
                - repetitions: 10
                  weight: 50
                - repetitions: 8
                  weight: 55
                - repetitions: 6
                  weight: 60
              - exercise_name: Suicide Squat
                sets:
                - repetitions: 12
                  weight: 100
                - repetitions: 10
                  weight: 110
                - repetitions: 8
                  weight: 120
            id_user: 30
          - id_history: 3
            created_at: '2024-12-09T03:21:02.104512+00:00'
            detil_history:
              date: '2024-12-05'
              duration: 1h 30m
              exercises:
              - exercise_name: lever seated fly
                sets:
                - repetitions: 10
                  weight: 50
                - repetitions: 8
                  weight: 55
                - repetitions: 6
                  weight: 60
              - exercise_name: concentrated curl
                sets:
                - repetitions: 12
                  weight: 100
                - repetitions: 10
                  weight: 110
                - repetitions: 8
                  weight: 120
            id_user: 30
    ReqBodyUpdateHistory:
      type: object
      properties:
        detil_history:
          type: object
          example:
            date: '2024-12-05'
            duration: 1h 30m
            exercises:
            - exercise_name: dumbbell row on incline bench
              sets:
              - repetitions: 10
                weight: 50
              - repetitions: 8
                weight: 55
              - repetitions: 6
                weight: 60
            - exercise_name: concentrated curl
              sets:
              - repetitions: 12
                weight: 100
              - repetitions: 10
                weight: 110
              - repetitions: 8
                weight: 120
    ReqBodyLogin:
      type: object
      properties:
        email:
          type: string
          example: 'john@email.com'
        password:
          type: string
          example: '12345'
    ReqBodyUpdateUser:
      type: object
      properties:
        gender:
          type: string
          example: 'L'
        berat_badan:
          type: integer
          example: 12.1
        tinggi_badan:
          type: integer
          example: 13.3
        name:
          type: string
          example: 'qwe'
    ReqBodyForgotPass:
      type: object
      properties:
        email:
          type: string
          example: john@email.com
    ReqBodyResetPass:
      type: object
      properties:
        email:
          type: string
          example: john@email.com
        resetCode:
          type: string
          example: 8908
        newPassword:
          type: string
          example: iamsohandsome
    ReqBodyCreatePlan:
      type: object
      properties:
        id_user:
          type: integer
          example: 30
        id_exercise:
          type: integer
          example: 24
        tanggal:
          type: string
          format: date
          example: 2021-12-23
        repetisi:
          type: integer
          example: 1
    ReqBodyUpdatePlan:
      type: object
      properties:
        id_exercise:
          type: integer
          example: 24
        tanggal:
          type: string
          format: date
          example: 2021-12-23
        repetisi:
          type: integer
          example: 1
    TokenLogin:
      type: object
      properties:
        data:
          type: object
          example:
            token: '{token}'
    UserData:
      type: object
      properties:
        name:
          type: string
          example: toni
        phone_number:
          type: string
          example: 089273847283
        gender:
          type: string
          example: P
        berat_badan:
          type: number
          example: 9.11
        tinggi_badan:
          type: number
          example: 21.2
    ForgotPassMessage:
      type: object
      properties:
        message:
          type: string
          example: Verification code sent to your email
        data:
          type: string
          example: null
    ResetPassMessage:
      type: object
      properties:
        message:
          type: string
          example: Password reset successful
        data:
          type: string
          example: null
    DeleteUserMessage:
      type: object
      properties:
        message:
          type: string
          example: User deleted successfully
        data:
          type: string
          example: null
    RegisterDataResp:
      type: object
      properties:
        data:
          type: object
          example:
            loginData:
            - created_at: '2024-12-09T13:12:27.114836+00:00'
              password: c02495df71a7c4805943e1ed7a067dbd2601ab6773d1001b875da139877aec63a465fa4911228e816ea3491bda60765742713d02fa93724e89295c887b1cad4b
              email: rayaprasetya90@gmail.com
              reset_code: null
              reset_code_expired: null
            userData:
            - id_user: 34
              created_at: '2024-12-09T13:12:26.994095+00:00'
              gender: P
              berat_badan: 12.1
              tinggi_badan: 13.3
              email: rayaprasetya90@gmail.com
              phone_number: 9210393
              name: goks
  securitySchemes:
    gymer_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://exercisehistory3.swagger.io/oauth/authorize
          scopes:
            write:exercises: modify exercises in your account
            read:exercises: read your exercises